### ISSUE TITLE
请求使港澳台搜索遵循哔哩哔哩官方搜索接口路径

### ISSUE THREAD

**Issue by ghost** [gamekingv/bilibili-oversea-search#2]
`api.qiu.moe`已支援主站港澳台及中国大陆搜索
请求示例:`https://api.qiu.moe/x/web-interface/search/type?search_type=media_bangumi&keyword=进击的巨人&area=tw`
`area`可选`cn`,`hk`,`tw`,以获取对应地区的搜索结果

**Comment by gamekingv** [comment]
已更新

**Comment by BraveSail** [comment]
> 已更新

可否把access_key也传递到代理服务器上

**Comment by gamekingv** [comment]
> > 已更新
> 
> 可否把access_key也传递到代理服务器上

access_key在哪，我在原始请求里也没找到

**Comment by BraveSail** [comment]
> > > 已更新
> > 
> > 
> > 可否把access_key也传递到代理服务器上
> 
> access_key在哪，我在原始请求里也没找到

搞错了 没事了（

**Comment by BraveSail** [comment]
> 已更新

看了下，海外接口没有传递area=th参数

**Comment by gamekingv** [comment]
> > 已更新
> 
> 看了下，海外接口没有传递area=th参数

海外整个路径和参数都不一样，还需要带area来区分吗？

**Comment by BraveSail** [comment]
我是按照area分流的，不过按照host分流也可以

**Comment by gamekingv** [comment]
> 我是按照area分流的，不过按照host分流也可以

我现在加area上去了，你看看有没用

**Comment by BraveSail** [comment]
可以了

**Comment by BraveSail** [comment]
海外区搜索结果番剧地址是 
`https://bangumi.bilibili.com/anime/1010375`
这种格式，实际上大部分海外区番剧并没有主站的bangumi页面，因此无法跳转到
`https://www.bilibili.com/bangumi/play/ss1010375`
这种可以通过解除区域限制脚本播放的页面，~~不知道能否做到替换URL为上述地址？~~

**Comment by gamekingv** [comment]
> 海外区搜索结果番剧地址是 `https://bangumi.bilibili.com/anime/1010375` 这种格式，实际上大部分海外区番剧并没有主站的bangumi页面，因此无法跳转到 `https://www.bilibili.com/bangumi/play/ss1010375` 这种可以通过解除区域限制脚本播放的页面，~不知道能否做到替换URL为上述地址？~

你可以用脚本打开这个地址？我记得现在已经打不开东南亚的了吧

**Comment by ghost** [comment]
https://www.bilibili.com/bangumi/play/ss1010375 可以打开，只是因为 cors 播放不了了

**Comment by gamekingv** [comment]
那可能是我用的代理问题，你们再试试，更新了

**Comment by BraveSail** [comment]
好了
