### ISSUE TITLE
除海外区外其他区搜不出东西

### ISSUE THREAD

**Issue by 1040302** [gamekingv/bilibili-oversea-search#6]
无论搜哪个番剧都没有，服务器和番剧在手机上可以正常使用，也能在网页上直接打开，但搜索只有海外区能搜到，包括大陆区也搜不到

**Comment by gamekingv** [comment]
测试过不带cookie进行搜索会被拦截，已修改代码。部分公共服务器可能会去掉cookie导致搜索被拦截，自建的测试过可以正常搜索

**Comment by KurosakiRei** [comment]
所以现在在代理服务器上加上cookie就行了对吧？
